-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;
CREATE TABLE IF NOT EXISTS public.actor (
    id integer NOT NULL DEFAULT nextval('actor_id_seq'::regclass),
    name character varying COLLATE pg_catalog."default" NOT NULL,
    gender character varying COLLATE pg_catalog."default" NOT NULL,
    date_birth timestamp without time zone NOT NULL,
    nationality character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT actor_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.movie (
    id integer NOT NULL DEFAULT nextval('movie_id_seq'::regclass),
    title character varying COLLATE pg_catalog."default" NOT NULL,
    type_id integer NOT NULL,
    CONSTRAINT movie_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.movie_type (
    id integer NOT NULL DEFAULT nextval('movie_type_id_seq'::regclass),
    type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT movie_type_pkey PRIMARY KEY (id)
);
CREATE TABLE IF NOT EXISTS public.performance (
    id integer NOT NULL DEFAULT nextval('performance_id_seq'::regclass),
    actor_id integer NOT NULL,
    movie_id integer NOT NULL,
    release_date timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT performance_pkey PRIMARY KEY (id)
);
ALTER TABLE IF EXISTS public.movie
ADD CONSTRAINT movie_type_id_fkey FOREIGN KEY (type_id) REFERENCES public.movie_type (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.performance
ADD CONSTRAINT performance_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public.actor (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE IF EXISTS public.performance
ADD CONSTRAINT performance_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public.movie (id) MATCH SIMPLE ON UPDATE NO ACTION ON DELETE NO ACTION;
END;