"""empty message

Revision ID: a8f09159460a
Revises: 
Create Date: 2022-12-27 11:18:49.093642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8f09159460a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('age', sa.Integer(), nullable=False))
    op.drop_column('actor', 'date_birth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('actor', sa.Column('date_birth', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('actor', 'age')
    # ### end Alembic commands ###
